# Generated by Django 2.0 on 2020-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200415_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='https://f0.pngfuel.com/png/184/113/portrait-icon-user-profile-computer-icons-profile-png-clip-art.png', null=True, upload_to='user_photos/'),
        ),
    ]
