# Generated by Django 2.0 on 2020-04-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200415_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
